name: pumpkin_bites_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: 3.13.0
  firebase_auth: 5.5.2
  cloud_firestore: 5.6.6
  firebase_storage: 12.4.5
  cloud_functions: ^5.2.5
  
  # UI
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # Audio
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  audio_session: ^0.1.16
  rxdart: ^0.27.7
  
  # Sharing
  share_plus: ^7.2.1
  
  # Subscription
  in_app_purchase: ^3.1.13
  
  # Utils
  intl: ^0.18.1
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  http: ^1.1.0
  
  # Image Generation
  screenshot: ^3.0.0
  image_picker: ^1.0.4

  get_it: ^7.6.4
  logger: ^2.0.2
  flutter_bloc: ^8.1.3  # For state management
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/icons/wine_stain_ring.svg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/steam_icon_1024.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo/steam_icon_1024.png"

flutter_native_splash:
  color: "#FFF8F3"
  image: "assets/images/logo/pumpkin_bites_logo_cream.png"
  color_dark: "#FFF8F3"
  image_dark: "assets/images/logo/pumpkin_bites_logo_cream.png"
  
  android_12:
    image: "assets/images/logo/steam_icon_1024.png"
    color: "#FFF8F3"